spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://voditeam.c2gj1gfl1vpz.us-east-1.rds.amazonaws.com/voidteam
    username: "admin"
    password: "03100310"
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

  h2:
    console:
      enabled: true
      path: /console

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB

security:
  require-ssl: true

server:
  port: 8090
  ssl:
    enabled: true
    key-store: classpath:voidteam.jks
    key-store-password: test1234
    key-store-type: JKS
    keyAlias: voidteam
  http:
    port: 8080


  compression:
    enabled: true
    mime-types: multipart/form-data,text/plain,application/json,  application/octet-stream, image/heic, image/jpeg, image/png, image/**


cloud:
  aws:
    s3:
      bucket: voidteam
    credentials:
      access-key: AKIA6JM6FNH7VJIGHL4U
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false


jwt:
  secret : "void"
  access:
    expiration: 604800000
    header: Authorization